### ISSUE TITLE
Fixed unused variable compiler warning in stm32f4xx_ll_adc.h for function LL_ADC_DMA_GetRegAddr

### ISSUE THREAD

**Issue by gerardhale** [STMicroelectronics/stm32f4xx_hal_driver#16]
Fixed unused variable compiler warning in stm32f4xx_ll_adc.h for function LL_ADC_DMA_GetRegAddr when ADC_MULTIMODE_SUPPORT not defined

we are compiling the stm32f4xx_hal_drvier as a library 
to test our HAL on the stm32f401 dev board

Building CXX object hal/CMakeFiles/hal_platfor...m32f401.dir/platforms/stm32f4_hal/src/HalGpioF4.cpp.obj
In file included from ../../platforms/stm32f4_hal/stm32f4xx_hal_driver/Inc/stm32f4xx_hal_adc.h:31,
                 from ../../platforms/stm32f4_hal/custom/inc/stm32f4xx_hal_conf.h:300,
                 from ../../platforms/stm32f4_hal/stm32f4xx_hal_driver/Inc/stm32f4xx_hal.h:29,
                 from ../../hal/platforms/stm32f4_hal/src/HalGpioF4.cpp:9:
../../platforms/stm32f4_hal/stm32f4xx_hal_driver/Inc/stm32f4xx_ll_adc.h: In function 'uint32_t LL_ADC_DMA_GetRegAddr(ADC_TypeDef*, uint32_t)':
../../platforms/stm32f4_hal/stm32f4xx_hal_driver/Inc/stm32f4xx_ll_adc.h:1880:76: warning: unused parameter 'Register' [-Wunused-parameter]

**How to reproduce the bug (skip if none)**
compile the hal_driver without defining ADC_MULTIMODE_SUPPORT and using  -Wunused-parameter

**Comment by ASELSTM** [comment]
Hi @gerardhale,

This same issue has been already reported [#116](https://github.com/STMicroelectronics/STM32CubeF4/issues/116), it has been fixed and published on GitHub. The fix is available on [stm32f4xx_hal_driver](https://github.com/STMicroelectronics/stm32f4xx_hal_driver) repository within this [commit](https://github.com/STMicroelectronics/stm32f4xx_hal_driver/commit/3080e579198674dc0c64622277ae0a97d0be9a81).

As fixed, please allow me this to close this thread and thank you for your contribution. 

With regards,
